export function QADashboardPage() {
  return (
    <div data-testid="qa-dashboard-page" className="space-y-4">
      <h1 className="text-2xl font-bold text-slate-900">QA Metrics Dashboard</h1>
      <p className="text-slate-600">
        Live quality metrics are generated by the QA automation suite. Run{" "}
        <code className="rounded bg-slate-100 px-1.5 py-0.5 text-sm">./scripts/run-all-qa.sh</code>{" "}
        from the <code className="rounded bg-slate-100 px-1.5 py-0.5 text-sm">qa-automation</code> folder.
      </p>
      <iframe
        title="QA Dashboard"
        src="/qa-dashboard.html"
        className="h-[70vh] w-full rounded-xl border border-slate-200 bg-slate-900"
      />
    </div>
  );
}
